version: '2'
services:
  project22-app:
    image: project22
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://project22-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=project22
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  project22-mongodb:
    extends:
      file: mongodb.yml
      service: project22-mongodb
